feat: signup to supabase auth
ecvdbdx/labo-union pull request #8
Opened 2022-12-20 15:14 UTC by ValMgr

- [x] basic form
- [x] request supabase to create user
- [x] handle password and mail validators 
- [x] handle errors
- [ ] create layout around form

2022-12-21 17:26 UTC, iOiurson requested changes

2022-12-21 17:26 UTC, iOiurson commented on src/app.d.ts
> +		Database: import('./DatabaseDefinitions').Database;
I don't know what this import is. I don't see it anywhere.

Also, i'm not sure these Supabase typings should live in this file.

Generally, this `app.d.ts` file should rather be for SvelteKit specific type definitions.

2022-12-21 17:26 UTC, iOiurson commented on src/routes/+page.svelte
> +	import { goto } from '$app/navigation';
Just a detail, but i like my imports to have a specific order:
- Svelte stuff
- SvelteKit stuff
- Types
- Helpers
- General components
- Page specific components

This is just a proposal for this project, we can discuss it in class.

2022-12-21 17:26 UTC, iOiurson commented on src/routes/+page.svelte
> +	<Button on:click={() => goto('/inscription', { replaceState: true })}>S'enregister</Button>
I believe this should be a `<a>` or a `<Link>`

2023-01-13 12:38 UTC, clemcode requested changes

2023-01-13 12:38 UTC, clemcode commented on src/lib/components/forms/Input.svelte
> -			<slot>Label*</slot>
Required fields should be specified via HTML (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required) and not hard-coded as string.

2023-01-13 12:38 UTC, clemcode commented on src/routes/inscription/+page.server.ts
> +}
These functions will be useful for other features, maybe we can extract them in a utils file to make them simpler to discover / reuse?

2023-01-16 08:28 UTC, closed without merging