feat: signup to supabase auth 👤
ecvdbdx/labo-union pull request #9
Opened 2023-01-16 08:28 UTC by ValMgr

- [x] basic form
- [x] request supabase to create user
- [x] handle password and mail validators 
- [x] handle errors
- [x] handle successfull sign-up
- [x] check if email exists in ECV students list
- [x] create layout around form

Rebase #8

2023-01-16 20:00 UTC, iOiurson requested changes

2023-01-18 08:50 UTC, iOiurson requested changes

2023-01-18 08:50 UTC, iOiurson commented on src/routes/+layout.ts
> +	return { session, supabaseClient };
Is it necessary to have `supabaseClient` sent as layout data when we can import it directly from `$lib/auth` ?

2023-01-27 15:13 UTC, ECV-bdx-dev approved these changes

2023-01-27 15:14 UTC, ECV-bdx-dev approved these changes

2023-01-27 15:14 UTC, ECV-bdx-dev approved these changes

2023-01-27 15:15 UTC, merged